### ISSUE TITLE
Tail segments in queue are never transmitted

### ISSUE THREAD

**Issue by tmick0** [le1ca/RIOT#3]
In this example, segment 10 is not transmitted. It is therefore not acked, then the queue is purged.

Remote node:
2015-08-07 13:44:05,328 - INFO # [rt] incoming probe from 631b
2015-08-07 13:44:05,829 - INFO # [rt] incoming poll from 631b
2015-08-07 13:44:05,833 - INFO # [ra] constructed packet of size 1258
2015-08-07 13:44:13,770 - INFO # [rt] pkg 9 seg 10 failed to transmit
2015-08-07 13:44:13,777 - INFO # [rt] removed 4 additional segments

Base station:
Sending probe (0)...
ACKing d5d9/8.0
Join from d5d9.
Sending poll to d5d9
ACKing d5d9/9.0
ACKing d5d9/9.1
ACKing d5d9/9.2
ACKing d5d9/9.3
ACKing d5d9/9.4
ACKing d5d9/9.5
ACKing d5d9/9.6
ACKing d5d9/9.7
ACKing d5d9/9.8
ACKing d5d9/9.9

**Comment by tmick0** [comment]
Further investigation indicates that the failed packet in question is being transmitted (or at least making it to the xbee driver...) but never received at the base station... This problem could be on either side.

**Comment by tmick0** [comment]
Not fixed.

Definitely something strange going on... increasing the number of retransmits does not help.

This occurs only in about 1 out of every 10 data packages.

**Comment by le1ca** [comment]
Definitely something strange going on... increasing the number of retransmits does not help

**Comment by tmick0** [comment]
Issue appears to be on the base station side. XBee adapter's LED indicates receipt of packets, but packets are not delivered to the driver.

**Comment by tmick0** [comment]
I think this one is fixed on the base station end. However, issue #4 has reemerged with the same symptoms as this.
